### PR TITLE
feat added endpoint to return logfile

### LINKED ISSUE #4: [option] endpoint to return log file
* /file/:file_path endpoint
* write file of file_path in response.getWriter()
* set header to 
```
Content-Type: text/plain
Content-Disposition: inline; filename="filename"
```

### PR DESCRIPTION
**Pull request by sork01**
fix #4

### CODE REVIEW

**Comment by sork01** [comment]
fixed the : and the github endpoint. 
Don't want to allow anything other than letters in the link since it's not safe.
Maybe another solution like getting lines from a single file could be implemented.

**Comment by Cpptz** [comment]
If you prepend the log directory to the file_path, you are sure that you restrict to that folder so why won't it be safe ?

**Comment by sork01** [comment]
It's not sure it's restricted to that directory. 
I'm not sure someone couldn't use filename to <cdup> out of the logs directory.

**Comment by Cpptz** [comment]
ok, I will just refractor to avoid that problem

**Pull request merged**
